- web/src-cordova/config.xml
- web/src-cordova/package-lock.json
- web/src-cordova/package.json
- web/src-cordova/yarn.lock
- web/src/main.js
> Fix facebook oauth

- .github/workflows/ci.yml
use yarn in github actions instead of npm
> ci: github actions yarn

- .gitignore
- LICENSE
- jest.config.js
- lint-staged.config.js
- package.json
> chore: jest coverage, lint staged and license config

- package.json
- src/environment.ts
- src/utils/api.ts
- yarn.lock
> chore: configure axios to call apis

- .github/PULL-REQUEST-TEMPLATE.md
Primeira versão de um template para Pull Request. Usei como base o template [deste repo](https://github.com/forem/forem/blob/main/.github/PULL_REQUEST_TEMPLATE.md) que li [neste artigo](https://dev.to/opensauced/how-to-create-a-good-pull-request-template-and-why-you-should-add-gifs-4i0l)
> docs: pull request template

- package-lock.json
- web/package.json
- web/src/pages/Recovery/Recovery.html
- web/src/pages/Recovery/Recovery.js
Atualmente, a página de recuperação não encontra alguns emails para recuperar acesso. O usuário insere o email institucional e, por algum motivo que não sabemos ainda, o email não é encontrado no banco de dados e o backend devolve um erro.
Este PR tem como objetivo induzir o usuário há uma ação depois de receber este erro. É uma pequena e temporária correção de UX a fim de instruir os novos usuários à entrarem em contato com o time do UFABC Next enquanto o backend segue trabalhando na correçao do bug.
[Link de demonstração do bug](https://wetransfer.com/downloads/af9913c5c160202782afddac1357a46520230529011010/989b57fceb03ef14eb7fc5aad7d7e95020230529011033/5534d7?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)
> fix: recovery error message

- .gitattributes
- apps/container/src/store/useAuth.ts
- apps/container/src/utils/composables/aliasInitials.ts
- apps/container/src/views/PerformanceView.vue
- apps/container/src/views/SettingsView.vue
- apps/react/webpack.config.js
- packages/services/users.ts
- packages/stores/auth/index.ts
Fechei o último PR (#120) para adaptar tudo o que estava lá na nova estrutura de microfrontend usando Tanstack para gerenciamento de estado. 
- Related Issue #114 
- Closes #114
> feat: settings page

- apps/container/src/views/Settings/SettingsView.vue
- apps/container/src/views/Stats/StatsView.vue
- packages/services/src/index.ts
- packages/tsconfig/base.json
- packages/utils/src/index.ts
Corrige os problemas de build do projeto e descarta a geração de arquivos .d.ts e .d.ts.map
> chore: build configs

- .github/workflows/cd.yml
Action responsável por fazer deploy em homologação
> ci: cd homolog

- .github/workflows/cd.yml
change turbo command to yarn and use format standard
> fix: cd build

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Add prod condition variables, also deploy only when CI pipeline is success
> chore: ci cd config prd

- apps/container/mf.config.js
- apps/react/webpack.config.js
Tentativa de correção do erro que ocorre ao carregar o microfrontend react no ambiente
> fix: mf dependencies

- apps/container/src/layouts/AppBar.vue
Adiciona as informações dinamicas do usuário ao header, além disso, mantem o comportamento se só mostrar o header quando o usuário for confirmado
> feat: header info

- apps/container/src/views/Reviews/ReviewsView.vue
Remove o justify-center para evitar layout shift quando for carregado as avaliações pendentes
> fix: reviews layout shift

- .github/workflows/integration-deploy.yml
> chore: add vercel cache

- apps/container/src/App.vue
- apps/container/src/layouts/AppBar/AppBar.test.ts
- apps/container/src/layouts/AppBar/AppBar.vue
Mostra a app bar apenas se o usuário está confirmado
> fix: show app bar logic

- apps/container/src/router/index.ts
Remove os dynamic imports no router que não funcionaram no ambiente
> fix: remove dynamic import

- apps/container/src/views/Facebook/FacebookView.vue
- Adicionando toast com notificação de conta nao encontrada user facebook
> release - 16/02/2024

- apps/container/src/views/Facebook/FacebookView.vue
- apps/static/index.html
- packages/services/src/api.ts
> O front atual apontava apenas para prod, dificultando testes em outros ambientes esse pr vem para corrigir isso
closes #310 
Rodar `yarn dev` e fazer login com o path do estatico em /apps/static/index.html deve redirecionar para o backend em `http://locahost:8011`
> Adiciona separação de ambientes ao front-end atual

- apps/container/src/views/Facebook/FacebookView.vue
- apps/container/src/views/Recovery/RecoveryView.vue
- apps/container/src/views/SignUp/SignUpView.vue
Corrigido validações faltantes nos campos de emails de formulários da aplicação
#312
> fix(form): whitespace form validation

- apps/container/src/views/Facebook/FacebookView.vue
- apps/container/src/views/Recovery/RecoveryView.vue
- apps/container/src/views/SignUp/SignUpView.vue
- apps/static/index.html
- packages/services/src/api.ts
Release 08/04/2024
- Separação de ambientes (dev, staging, prod)
- Feedback para o usuário em caso de erro na busca por conta do Facebook
> Release 08/04/2024

- apps/static/index.html
> fix: oauth url

- apps/container/src/views/Partners/NextClass/NextClassView.vue
Novo texto para os aulões next p2
> feat: auloes next p2

- apps/static/index.html
> fix: devlogin btn flick

- apps/container/src/views/Facebook/FacebookView.vue
- apps/container/src/views/SignUp/SignUpView.vue
- packages/services/src/users.ts
> wip: working on signup refactor

- packages/services/src/performance.ts
> fix: changing endpoint calls to solve frontend issue

- apps/container/src/views/History/HistoryView.vue
- packages/utils/src/consts.ts
> hotfix: change broken link

- apps/container/src/views/Recovery/RecoveryView.vue
- apps/container/src/views/SignUp/SignUpView.vue
- packages/services/src/users.ts
temporary fix
some TS issues, but will resolve in remove microfrontend pr
> fix: recovery ufabc next account

- apps/container/src/views/Calengrade/screens/PreviewScreen.vue
Resolve problema de acentuacao do Calengrade
> fix: calengrade enconding

- apps/static/index.html
adiciona compatibilidade com firefox da landing page em dev
> fix: improve local env assertions (firefox compatibility)

- apps/container/src/components/UserNotifications.vue
- apps/container/src/views/WhatsappGroups/WhatsappGroupsView.vue
> feat: whatsapp restriction dialog
